AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Simple serverless service"

Parameters:
  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - local
      - staging
    Description: The environment to be run on (typically local, dev, staging or prod)

  ServiceName:
    Type: String
    Description: The service name

  DataSourceName:
    Type: String
    Default: SimpleServiceStudentLambda
    Description: Simple service

  PrivateSubnet1:
    Type: AWS::SSM::Parameter::Value<String>
    Default: private-subnet-1

  PrivateSubnet2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: private-subnet-2

  PrivateSubnet3:
    Type: AWS::SSM::Parameter::Value<String>
    Default: private-subnet-3

  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: VPC ID created by bootstrapper
    Default: VpcId


Mappings:
  Environment:
    dev:
      LogLevel: "INFO"

    prod:
      LogLevel: "INFO"

Resources:

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-${StageName}
      Handler: lambda_function.handler
      Runtime: python3.8
      CodeUri: ./src
      Timeout: 35
      MemorySize: 128
      Tracing: Active
      Policies:

        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*

      Environment:
        Variables:
          STAGE: !Ref StageName
          LOG_LEVEL: !FindInMap [Environment, !Ref StageName, LogLevel]
          POWERTOOLS_SERVICE_NAME: simple-serverless


  # API Gateway (REST stuff) starts here

  APIGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub simple-rest-api-${StageName}
      ProtocolType: HTTP
      # Target: "https://this.forces.creation.of.a.default.stage"

  APIGatewayLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*/*/*"
    DependsOn:
      - APIGateway
      - LambdaFunction

  APIGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: $default
      Description: Default Stage
      AutoDeploy: true
      ApiId: !Ref APIGateway

  RestStudentIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref APIGateway
      IntegrationType: "AWS_PROXY"
      IntegrationUri: !GetAtt LambdaFunction.Arn
      PayloadFormatVersion: 2.0

  RestDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      RouteKey: "ANY /"
      ApiId: !Ref APIGateway
      Target: !Sub 'integrations/${RestStudentIntegration}'

  RestListStudentsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      RouteKey: "GET /students"
      ApiId: !Ref APIGateway
      Target: !Sub 'integrations/${RestStudentIntegration}'

  RestGetStudentRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      RouteKey: "GET /students/{studentId}"
      ApiId: !Ref APIGateway
      Target: !Sub 'integrations/${RestStudentIntegration}'

  RestSaveStudentRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      RouteKey: "POST /students/{studentId}"
      ApiId: !Ref APIGateway
      Target: !Sub 'integrations/${RestStudentIntegration}'



  # Appsync (GraphQL stuff) starts here

  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub simple-graphql-api-${StageName}
      AuthenticationType: API_KEY
      XrayEnabled: true

  GraphqlApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      Description: "Default API Key"
      ApiId: !GetAtt GraphQLApi.ApiId

  # Schema will get included with SAM PACKAGE command:
  Schema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: ./src/schema.graphql

  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AppSyncInvokeLambdas
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*

  LambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: !Sub ${DataSourceName}
      Description: !Sub ${ServiceName} lambda data source."
      Type: "AWS_LAMBDA"
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !Sub ${LambdaFunction.Arn}

  ListStudentsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: "listStudents"
      DataSourceName: !GetAtt LambdaDataSource.Name

  GetStudentsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: "getStudent"
      DataSourceName: !GetAtt LambdaDataSource.Name

  SaveStudentsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: "saveStudent"
      DataSourceName: !GetAtt LambdaDataSource.Name


Outputs:
  RestAPIOutput:
    Description: "The url of the rest api"
    Value: !GetAtt APIGateway.ApiEndpoint
    Export:
      Name: !Sub ${AWS::StackName}-RestApiUrl-${StageName}

  GraphQLApiIdOutput:
    Description: "The AppSync API ID"
    Value: !GetAtt GraphQLApi.ApiId
    Export:
      Name: !Sub ${AWS::StackName}-GraphQLApiId-${StageName}

  GraphQLUrlOutput:
    Description: "The GraphQL URL"
    Value: !GetAtt GraphQLApi.GraphQLUrl
    Export:
      Name: !Sub ${AWS::StackName}-GraphQLUrl-${StageName}

  GraphQLApiKeyOutput:
    Description: "Default API key"
    Value: !GetAtt GraphqlApiKey.ApiKey
    Export:
      Name: !Sub ${AWS::StackName}-GraphQLApiKey-${StageName}
